# Use an unofficial Python runtime as a parent image
FROM cnstark/pytorch:1.12.0-py3.9.12-cuda11.6.2-ubuntu20.04
RUN apt-get update && apt-get install


# Set the working directory to /app

WORKDIR /app

# Copy the current directory contents into the container at /app

COPY . /app

# Install any needed packages specified in requirements.txt

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container

EXPOSE 80

# Define environment variable
# ENV NAME World
